export default {
  '---form-inputs': { type: 'separator', title: 'Form Inputs' },
  checkbox: 'Checkbox',
  'checkbox-group': 'Checkbox Group',
  combobox: 'Combobox',
  'date-picker': 'Date Picker',
  'input-group': 'Input Group',
  'number-field': 'Number Field',
  'otp-field': 'OTP Field',
  'password-field': 'Password Field',
  'radio-group': 'Radio Group',
  'search-field': 'Search Field',
  select: 'Select',
  slider: 'Slider',
  switch: 'Switch',
  'text-field': 'Text Field',
  toggle: 'Toggle',
  'toggle-group': 'Toggle Group',
  '---actions-navigation': { type: 'separator', title: 'Actions & Navigation' },
  breadcrumbs: 'Breadcrumbs',
  button: 'Button',
  command: 'Command',
  'context-menu': 'Context Menu',
  'hover-trigger': 'Hover Trigger',
  'loading-button': 'Loading Button',
  menu: 'Menu',
  menubar: 'Menubar',
  navbar: 'Navbar',
  pagination: 'Pagination',
  tabs: 'Tabs',
  toolbar: 'Toolbar',
  'theme-button': 'Theme Button',
  'theme-switcher': 'Theme Switcher',
  '---feedback-status': { type: 'separator', title: 'Feedback & Status' },
  alert: 'Alert',
  'alert-dialog': 'Alert Dialog',
  'confirmation-dialog': 'Confirmation Dialog',
  dialog: 'Dialog',
  empty: 'Empty',
  loading: 'Loading',
  meter: 'Meter',
  modal: 'Modal',
  popover: 'Popover',
  'progress-bar': 'Progress Bar',
  'progress-circle': 'Progress Circle',
  sheet: 'Sheet',
  skeleton: 'Skeleton',
  'status-light': 'Status Light',
  toast: 'Toast',
  tooltip: 'Tooltip',
  '---data-display': { type: 'separator', title: 'Data Display' },
  accordion: 'Accordion',
  avatar: 'Avatar',
  badge: 'Badge',
  calendar: 'Calendar',
  carousel: 'Carousel',
  collapsible: 'Collapsible',
  'data-card': 'Data Card',
  'data-table': 'Data Table',
  icon: 'Icon',
  image: 'Image',
  kbd: 'Kbd',
  list: 'List',
  table: 'Table',
  'tag-group': 'Tag Group',
};
