export default {
  'alert-banner': 'Alert Banner',
  'alert-dialog': 'Alert Dialog',
  'confirmation-dialog': 'Confirmation Dialog',
  dialog: 'Dialog',
  'empty-state': 'Empty State',
  loading: 'Loading',
  meter: 'Meter',
  modal: 'Modal',
  popover: 'Popover',
  'progress-bar': 'Progress Bar',
  'progress-circle': 'Progress Circle',
  sheet: 'Sheet',
  skeleton: 'Skeleton',
  'status-light': 'Status Light',
  toast: 'Toast',
  tooltip: 'Tooltip',
};
