export default {
  accordion: 'Accordion',
  avatar: 'Avatar',
  badge: 'Badge',
  calendar: 'Calendar',
  carousel: 'Carousel',
  collapsible: 'Collapsible',
  'data-card': 'Data Card',
  'data-table': 'Data Table',
  icon: 'Icon',
  image: 'Image',
  list: 'List',
  table: 'Table',
  'tag-group': 'Tag Group',
};
