export default {
  accordion: 'Accordion',
  'alert-banner': 'Alert Banner',
  'alert-dialog': 'Alert Dialog',
  breadcrumbs: 'Breadcrumbs',
  button: 'Button',
  calendar: 'Calendar',
  checkbox: 'Checkbox',
  combobox: 'Combobox',
  'confirmation-dialog': 'Confirmation Dialog',
  'data-card': 'Data Card',
  'data-table': 'Data Table',
  dialog: 'Dialog',
  form: 'Form',
  'hover-trigger': 'Hover Trigger',
  icon: 'Icon',
  'icon-label': 'Icon Label',
  image: 'Image',
  'inline-edit-field': 'Inline Edit Field',
  list: 'List',
  loading: 'Loading',
  'loading-button': 'Loading Button',
  menu: 'Menu',
  modal: 'Modal',
  navbar: 'Navbar',
  'nav-menu': 'Nav Menu',
  'password-field': 'Password Field',
  popover: 'Popover',
  'progress-bar': 'Progress Bar',
  'progress-circle': 'Progress Circle',
  'radio-group': 'Radio Group',
  'search-field': 'Search Field',
  select: 'Select',
  sidebar: 'Sidebar',
  slider: 'Slider',
  'status-light': 'Status Light',
  switch: 'Switch',
  table: 'Table',
  tabs: 'Tabs',
  'text-field': 'Text Field',
  'theme-button': 'Theme Button',
  toast: 'Toast',
  toggle: 'Toggle',
  'toggle-group': 'Toggle Group',
  tooltip: 'Tooltip',
};
