export default {
  '-- Form Inputs': {
    type: 'separator',
    title: 'Form Inputs',
  },
  checkbox: 'Checkbox',
  combobox: 'Combobox',
  'password-field': 'Password Field',
  'radio-group': 'Radio Group',
  'search-field': 'Search Field',
  select: 'Select',
  slider: 'Slider',
  switch: 'Switch',
  'text-field': 'Text Field',
  toggle: 'Toggle',
  'toggle-group': 'Toggle Group',

  '-- Actions & Navigation': {
    type: 'separator',
    title: 'Actions & Navigation',
  },
  breadcrumbs: 'Breadcrumbs',
  button: 'Button',
  'hover-trigger': 'Hover Trigger',
  'loading-button': 'Loading Button',
  menu: 'Menu',
  'nav-menu': 'Nav Menu',
  navbar: 'Navbar',
  sidebar: 'Sidebar',
  tabs: 'Tabs',
  'theme-button': 'Theme Button',

  '-- Feedback & Status': {
    type: 'separator',
    title: 'Feedback & Status',
  },
  'alert-banner': 'Alert Banner',
  'alert-dialog': 'Alert Dialog',
  'confirmation-dialog': 'Confirmation Dialog',
  dialog: 'Dialog',
  loading: 'Loading',
  modal: 'Modal',
  popover: 'Popover',
  'progress-bar': 'Progress Bar',
  'progress-circle': 'Progress Circle',
  'status-light': 'Status Light',
  toast: 'Toast',
  tooltip: 'Tooltip',

  '-- Data Display': {
    type: 'separator',
    title: 'Data Display',
  },
  accordion: 'Accordion',
  calendar: 'Calendar',
  'data-card': 'Data Card',
  'data-table': 'Data Table',
  icon: 'Icon',
  'icon-label': 'Icon Label',
  image: 'Image',
  list: 'List',
  table: 'Table',
};
